### ISSUE TITLE
unhandled exception when disconnecting during calibration

### ISSUE THREAD

**Issue by HaythamB** [HaythamB/TAMV#49]
If TAMV is in the middle of running and the user clicks disconnect, it throws an error 0x00:
```
line 1136: (c, transform, mpp) = self.calibrateTool(int(ptool['number']), rep)
line 1528: (self.xy, self.taget, self.tool_coordinates, self.radius) = self.analyzeFrame()
TypeError: cannot unpack non-iterable object NoneType object
```

Need to handle the printer disconnecting during a calibration to catch this.

**Comment by HaythamB** [comment]
```
Traceback (most recent call last):
  File "c:\Users\hayth\Documents\GitHub\TAMV\TAMV_GUI.py", line 1211, in run
    self.calibrateTool(ctool='endstop', rep=1)
  File "c:\Users\hayth\Documents\GitHub\TAMV\TAMV_GUI.py", line 1534, in calibrateTool
    (self.xy, self.tool_coordinates) = self.analyzeEndstop()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by HaythamB** [comment]
added exception handling to catch the user cancelling operations while they're running.
